# Generated by Django 3.1.3 on 2020-11-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Author',
            field=models.CharField(default='Author', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='Tag',
            field=models.CharField(choices=[('Fc', 'Team, Clubs n Societies'), ('Ed', 'Educational'), ('Ra', 'Random')], default='Ra', max_length=2),
        ),
    ]
